[tool.mypy]
files = "**/*.py"
strict = true
implicit_reexport = true

[tool.ruff]
ignore = ["D", "EM", "T201", "TCH001", "TRY003"]
select = ["ALL"]
target-version = "py311"

[tool.ruff.per-file-ignores]
"mock_data.py" = ["E501"]
"test_*.py" = ["S101", "TID252"]
