[tool.mypy]
files = "**/*.py"
strict = true
implicit_reexport = true

[tool.ruff]
target-version = "py38"

[tool.ruff.lint]
ignore = ["COM812", "D", "EM", "ISC001", "T201", "TCH001", "TRY003"]
select = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"mock_data.py" = ["E501"]
"test_*.py" = ["S101", "TID252"]
